steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        gcloud functions deploy message-bot \
          --runtime nodejs18 \
          --region=us-central1 \
          --source=. \
          --trigger-http \
          --entry-point app \
          --set-env-vars TELEGRAM_TOKEN=$(gcloud secrets versions access latest --secret=TELEGRAM_MESSAGE_BOT_TOKEN)
options:
  logging: CLOUD_LOGGING_ONLY
